FROM python:3.7

WORKDIR /usr/src/app

COPY . .

RUN apt-get update  \
    && pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

EXPOSE 5001

CMD ["gunicorn", "app:app", "-c", "./gunicorn.conf.py"]